//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AzureIntegrationMigration.Tool.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AzureIntegrationMigration.Tool.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ValidationErrorCount} command line arguments failed validation..
        /// </summary>
        internal static string ArgumentsFailedValidation {
            get {
                return ResourceManager.GetString("ArgumentsFailedValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {ValidationError}.
        /// </summary>
        internal static string ArgumentValidationError {
            get {
                return ResourceManager.GetString("ArgumentValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to build runner: {ErrorMessage}.
        /// </summary>
        internal static string FailedBuildingRunner {
            get {
                return ResourceManager.GetString("FailedBuildingRunner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed deserializing model {ModelFile}: {ErrorMessage}.
        /// </summary>
        internal static string FailedDeserializingModel {
            get {
                return ResourceManager.GetString("FailedDeserializingModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse command line args.
        ///{Message}.
        /// </summary>
        internal static string FailedParsingCommandLineArgs {
            get {
                return ResourceManager.GetString("FailedParsingCommandLineArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find a model provider..
        /// </summary>
        internal static string FailedToFindModelProvider {
            get {
                return ResourceManager.GetString("FailedToFindModelProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed loading model {0}..
        /// </summary>
        internal static string FailedToLoadModel {
            get {
                return ResourceManager.GetString("FailedToLoadModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find path {0} does not exist..
        /// </summary>
        internal static string FindPathDoesNotExist {
            get {
                return ResourceManager.GetString("FindPathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full exception details:.
        /// </summary>
        internal static string FullExceptionDetails {
            get {
                return ResourceManager.GetString("FullExceptionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model in file {0} does not contain a valid model type..
        /// </summary>
        internal static string ModelFileDoesNotContainAnApplicationModel {
            get {
                return ResourceManager.GetString("ModelFileDoesNotContainAnApplicationModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model file {0} does not exist..
        /// </summary>
        internal static string ModelFileDoesNotExist {
            get {
                return ResourceManager.GetString("ModelFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A model file must be specified when converting a model..
        /// </summary>
        internal static string ModelFileMustBeSpecified {
            get {
                return ResourceManager.GetString("ModelFileMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin path {PluginPath} does not exist..
        /// </summary>
        internal static string PluginPathDoesNotExist {
            get {
                return ResourceManager.GetString("PluginPathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary and secondary regions must be set to different values..
        /// </summary>
        internal static string PrimaryAndSecondaryRegionsIdentical {
            get {
                return ResourceManager.GetString("PrimaryAndSecondaryRegionsIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid region..
        /// </summary>
        internal static string RegionDoesNotExist {
            get {
                return ResourceManager.GetString("RegionDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A runner error occurred: {ErrorMessage}.
        /// </summary>
        internal static string RunnerErrorOccurred {
            get {
                return ResourceManager.GetString("RunnerErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify one of the following commands: {Assess}, {Migrate}, {Convert} or {Verify}..
        /// </summary>
        internal static string SpecifyVerb {
            get {
                return ResourceManager.GetString("SpecifyVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage runner {StageRunner} failed with error: {Error}.
        /// </summary>
        internal static string StageRunnerFailed {
            get {
                return ResourceManager.GetString("StageRunnerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template configuration path {0} does not exist..
        /// </summary>
        internal static string TemplateConfigPathDoesNotExist {
            get {
                return ResourceManager.GetString("TemplateConfigPathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template path {0} does not exist..
        /// </summary>
        internal static string TemplatePathDoesNotExist {
            get {
                return ResourceManager.GetString("TemplatePathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected runner error occurred: {ErrorMessage}.
        /// </summary>
        internal static string UnexpectedRunnerErrorOccurred {
            get {
                return ResourceManager.GetString("UnexpectedRunnerErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique deployment ID {0} must be alphanumeric characters only..
        /// </summary>
        internal static string UniqueDeploymentIdIncorrectFormat {
            get {
                return ResourceManager.GetString("UniqueDeploymentIdIncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique deployment ID must be up to {0} non-whitespace alphanumeric characters or less..
        /// </summary>
        internal static string UniqueDeploymentIdLengthExceedsLimit {
            get {
                return ResourceManager.GetString("UniqueDeploymentIdLengthExceedsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working path {0} does not exist..
        /// </summary>
        internal static string WorkingPathDoesNotExist {
            get {
                return ResourceManager.GetString("WorkingPathDoesNotExist", resourceCulture);
            }
        }
    }
}
