// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AzureIntegrationMigration.Tool.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InformationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InformationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AzureIntegrationMigration.Tool.Resources.InformationMessages", typeof(InformationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort on first exception: {Abort}.
        /// </summary>
        internal static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort stage on any exception: {Stage}.
        /// </summary>
        internal static string AbortStage {
            get {
                return ResourceManager.GetString("AbortStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app has been cancelled..
        /// </summary>
        internal static string AppCancelled {
            get {
                return ResourceManager.GetString("AppCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument: name = {Name}, value = {Value}.
        /// </summary>
        internal static string Arg {
            get {
                return ResourceManager.GetString("Arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument delimiter: {ArgDelimiter}.
        /// </summary>
        internal static string ArgDelimiter {
            get {
                return ResourceManager.GetString("ArgDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {AssemblyCount} assemblies in {FindPath}..
        /// </summary>
        internal static string AssemblyCountInPath {
            get {
                return ResourceManager.GetString("AssemblyCountInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure primary region: {AzurePrimaryRegion}.
        /// </summary>
        internal static string AzurePrimaryRegion {
            get {
                return ResourceManager.GetString("AzurePrimaryRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure secondary region: {AzureSecondaryRegion}.
        /// </summary>
        internal static string AzureSecondaryRegion {
            get {
                return ResourceManager.GetString("AzureSecondaryRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure subscription ID: {AzureSubscriptionId}.
        /// </summary>
        internal static string AzureSubscriptionId {
            get {
                return ResourceManager.GetString("AzureSubscriptionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion path: {ConversionPath}.
        /// </summary>
        internal static string ConversionPath {
            get {
                return ResourceManager.GetString("ConversionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target deployment environment: {DeploymentEnvironment}.
        /// </summary>
        internal static string DeploymentEnv {
            get {
                return ResourceManager.GetString("DeploymentEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding model provider..
        /// </summary>
        internal static string FindingModelProvider {
            get {
                return ResourceManager.GetString("FindingModelProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding stage runners..
        /// </summary>
        internal static string FindingStageRunners {
            get {
                return ResourceManager.GetString("FindingStageRunners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find path: {FindPath}.
        /// </summary>
        internal static string FindPath {
            get {
                return ResourceManager.GetString("FindPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find pattern: {FindPattern}.
        /// </summary>
        internal static string FindPattern {
            get {
                return ResourceManager.GetString("FindPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No libraries found in {FindPath}..
        /// </summary>
        internal static string LibrariesNotFoundInPath {
            get {
                return ResourceManager.GetString("LibrariesNotFoundInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {LibraryCount} libraries in {FindPath}..
        /// </summary>
        internal static string LibraryCountFoundInPath {
            get {
                return ResourceManager.GetString("LibraryCountFoundInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total plugins loaded: {PluginCount}.
        /// </summary>
        internal static string LoadedPlugins {
            get {
                return ResourceManager.GetString("LoadedPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model file: {ModelFile}.
        /// </summary>
        internal static string ModelFile {
            get {
                return ResourceManager.GetString("ModelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output model file: {OutputModelFile}.
        /// </summary>
        internal static string OutputModelFile {
            get {
                return ResourceManager.GetString("OutputModelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default primary region {0} is not the paired region for the supplied secondary region {1}, changing the primary region to {2} as the paired region..
        /// </summary>
        internal static string PrimaryRegionChangedToMatchPairedRegionOfSecondary {
            get {
                return ResourceManager.GetString("PrimaryRegionChangedToMatchPairedRegionOfSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The runner has been cancelled..
        /// </summary>
        internal static string RunnerCancelled {
            get {
                return ResourceManager.GetString("RunnerCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running an assessment..
        /// </summary>
        internal static string RunningAssessment {
            get {
                return ResourceManager.GetString("RunningAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running a conversion..
        /// </summary>
        internal static string RunningConversion {
            get {
                return ResourceManager.GetString("RunningConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running a migration..
        /// </summary>
        internal static string RunningMigration {
            get {
                return ResourceManager.GetString("RunningMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running a verification..
        /// </summary>
        internal static string RunningVerification {
            get {
                return ResourceManager.GetString("RunningVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save execution state before and after each stage: {SaveStageState}.
        /// </summary>
        internal static string SaveStageState {
            get {
                return ResourceManager.GetString("SaveStageState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save execution state before and after each stage runner: {SaveState}.
        /// </summary>
        internal static string SaveState {
            get {
                return ResourceManager.GetString("SaveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning....
        /// </summary>
        internal static string ScanningLibraries {
            get {
                return ResourceManager.GetString("ScanningLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for {PluginType} in {FindPath}..
        /// </summary>
        internal static string SearchingPluginPath {
            get {
                return ResourceManager.GetString("SearchingPluginPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default secondary region {0} is not the paired region for the supplied primary region {1}, changing the secondary region to {2} as the paired region..
        /// </summary>
        internal static string SecondaryRegionChangedToMatchPairedRegionOfPrimary {
            get {
                return ResourceManager.GetString("SecondaryRegionChangedToMatchPairedRegionOfPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State path: {StatePath}.
        /// </summary>
        internal static string StatePath {
            get {
                return ResourceManager.GetString("StatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Integration Services target: {Target}.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template configuration path: {TemplateConfigPath}.
        /// </summary>
        internal static string TemplateConfigPath {
            get {
                return ResourceManager.GetString("TemplateConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template path: {TemplatePath}.
        /// </summary>
        internal static string TemplatePath {
            get {
                return ResourceManager.GetString("TemplatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique deployment ID: {UniqueDeploymentId}.
        /// </summary>
        internal static string UniqueDeploymentId {
            get {
                return ResourceManager.GetString("UniqueDeploymentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command: {CommandVerb}.
        /// </summary>
        internal static string Verb {
            get {
                return ResourceManager.GetString("Verb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose logging: {Verbose}.
        /// </summary>
        internal static string Verbose {
            get {
                return ResourceManager.GetString("Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose level: {VerboseLevel}.
        /// </summary>
        internal static string VerboseLevel {
            get {
                return ResourceManager.GetString("VerboseLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working path: {WorkingPath}.
        /// </summary>
        internal static string WorkingPath {
            get {
                return ResourceManager.GetString("WorkingPath", resourceCulture);
            }
        }
    }
}
